server:
  port: 7003
# Eureka配置
eureka:
  instance:
    hostname: Eureka7003 # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # 为false：表示自己为注册中心
    service-url: # web监控页面
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/